### ISSUE TITLE
Won't sync beyond block 811259

### ISSUE THREAD

**Issue by checksum0** [bcoin-org/lcoin#1]
Tried on beta13 and beta14 on windows.

Lcoin won't sync beyond block 811259 and declare a high number of orphan block, of which, after checking in a block explorer, most of them are not orphan at all. It also declare at least block 811268 as duplicate even though the chain tip is not there yet.

I also have at least one other peer running lcoin and he is too stuck at 811259 according to the version message.

[debug.log](https://github.com/bcoin-org/lcoin/files/1100796/debug.log.txt)

**Comment by chjj** [comment]
Caused by some bad network param defs. Should be fixed with v1.0.0-beta.15.

**Comment by checksum0** [comment]
Fixed.
